from __future__ import annotations

from .models import Patch, MaintenanceWindow

def load_sample():
    windows = [
        MaintenanceWindow(
            id="w1",
            title="Window 1 (Sun 01:00–03:00)",
            start_iso="2026-01-04T01:00:00+05:30",
            end_iso="2026-01-04T03:00:00+05:30",
            downtime_budget_minutes=90,
            eng_cost_budget=6.0,
        ),
        MaintenanceWindow(
            id="w2",
            title="Window 2 (Wed 23:00–01:00)",
            start_iso="2026-01-07T23:00:00+05:30",
            end_iso="2026-01-08T01:00:00+05:30",
            downtime_budget_minutes=60,
            eng_cost_budget=5.0,
        ),
        MaintenanceWindow(
            id="w3",
            title="Window 3 (Sat 02:00–04:00)",
            start_iso="2026-01-10T02:00:00+05:30",
            end_iso="2026-01-10T04:00:00+05:30",
            downtime_budget_minutes=120,
            eng_cost_budget=8.0,
        ),
    ]

    patches = [
        Patch(
            id="p1",
            name="OpenSSL 3.x patch",
            asset="API Gateway",
            asset_criticality=5,
            cve="CVE-2025-10001",
            cvss=9.8,
            epss_like=0.78,
            kev=True,
            downtime_minutes=20,
            eng_cost=2.0,
            change_risk=0.12,
            depends_on=[],
        ),
        Patch(
            id="p2",
            name="Kernel LTS security update",
            asset="Payments DB",
            asset_criticality=5,
            cve="CVE-2025-11011",
            cvss=8.8,
            epss_like=0.35,
            kev=False,
            downtime_minutes=45,
            eng_cost=3.5,
            change_risk=0.22,
            depends_on=[],
        ),
        Patch(
            id="p3",
            name="Nginx HTTP/2 fix",
            asset="Public Web",
            asset_criticality=4,
            cve="CVE-2025-12003",
            cvss=7.5,
            epss_like=0.60,
            kev=False,
            downtime_minutes=10,
            eng_cost=1.0,
            change_risk=0.08,
            depends_on=[],
        ),
        Patch(
            id="p4",
            name="Java Log4j minor hardening",
            asset="Analytics Worker",
            asset_criticality=3,
            cve="CVE-2025-13004",
            cvss=6.5,
            epss_like=0.12,
            kev=False,
            downtime_minutes=15,
            eng_cost=1.5,
            change_risk=0.10,
            depends_on=[],
        ),
        Patch(
            id="p5",
            name="PostgreSQL auth bypass fix",
            asset="Payments DB",
            asset_criticality=5,
            cve="CVE-2025-14005",
            cvss=9.1,
            epss_like=0.42,
            kev=True,
            downtime_minutes=35,
            eng_cost=3.0,
            change_risk=0.20,
            depends_on=["p2"],  # kernel update first
        ),
        Patch(
            id="p6",
            name="Redis RCE patch",
            asset="Session Cache",
            asset_criticality=4,
            cve="CVE-2025-15006",
            cvss=8.0,
            epss_like=0.55,
            kev=False,
            downtime_minutes=25,
            eng_cost=2.0,
            change_risk=0.15,
            depends_on=["p1"],  # depends on OpenSSL for TLS stack alignment (example)
        ),
        Patch(
            id="p7",
            name="Ubuntu OpenSSH patch",
            asset="Bastion Host",
            asset_criticality=5,
            cve="CVE-2025-16007",
            cvss=9.0,
            epss_like=0.50,
            kev=False,
            downtime_minutes=15,
            eng_cost=1.0,
            change_risk=0.12,
            depends_on=[],
        ),
        Patch(
            id="p8",
            name="Node.js dependency update (lodash)",
            asset="Public Web",
            asset_criticality=4,
            cve="CVE-2025-17008",
            cvss=5.9,
            epss_like=0.25,
            kev=False,
            downtime_minutes=5,
            eng_cost=0.5,
            change_risk=0.05,
            depends_on=["p3"],
        ),
        Patch(
            id="p9",
            name="Kubernetes API server patch",
            asset="K8s Control Plane",
            asset_criticality=5,
            cve="CVE-2025-18009",
            cvss=8.6,
            epss_like=0.30,
            kev=False,
            downtime_minutes=40,
            eng_cost=3.0,
            change_risk=0.28,
            depends_on=[],
        ),
        Patch(
            id="p10",
            name="Grafana auth fix",
            asset="Observability",
            asset_criticality=3,
            cve="CVE-2025-19010",
            cvss=7.2,
            epss_like=0.18,
            kev=False,
            downtime_minutes=10,
            eng_cost=1.0,
            change_risk=0.08,
            depends_on=[],
        ),
    ]
    return windows, patches
